// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewOrder struct {
	Name         string         `json:"name"`
	Address      string         `json:"address"`
	Phone        string         `json:"phone"`
	OrderedItems []*NewShopItem `json:"ordered_items"`
}

type NewShopItem struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	ImageURL    string  `json:"image_url"`
}

type Order struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	Address      string      `json:"address"`
	Phone        string      `json:"phone"`
	OrderedItems []*ShopItem `json:"ordered_items"`
}

type ShopItem struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	ImageURL    string  `json:"image_url"`
}
